python -u main.py \
--gpus 0,1,2,3 \
--model resnet18_1w1a \
--results_dir ./result \
--data_path [DATA_PATH] \
--dataset imagenet \
--epochs 256 \
--lr 1e-3 \
--optimizer adam \
--lr_type linear \
-b 512 \
-bt 256 \
--lr_type cos \
--warm_up \
--weight_decay 0. \
--tau_min 0.85 \
--tau_max 0.99 \
--teacher resnet34 \
--stage1 [stage1_model] \